VALID_UNDERSTANDING = {
    "safe": True,
    "unsafe_category": None,
    "simulatable": True,
    "reason_code": "ok",
    "lang": "ar",
    "canonical_intent": "moon_phase_lit_fraction",
    "domain": "astronomy",
    "title": "لماذا يتغير شكل القمر؟",
    "tldr": "يتغير الجزء المضيء الذي نراه لأن موضع القمر يتغير بالنسبة إلى الأرض والشمس.",
    "key_formula": "f = (1 - cos θ) / 2",
    "learning_objective": "ربط زاوية المدار بالجزء المضيء المرئي",
    "primary_parameter": {
        "id": "angle_deg",
        "label": "زاوية القمر",
        "unit": "°",
        "min": 0,
        "max": 360,
        "default": 90,
        "step": 1,
    },
    "secondary_parameter": None,
    "prediction": {
        "prompt": "عند زيادة الزاوية، هل يكبر الجزء المضيء أولًا؟",
        "choices": ["نعم", "لا"],
    },
    "misconception": "ظل الأرض هو سبب أطوار القمر",
    "explanation_prompt": "تغيّر الجزء المضيء لأن…",
    "transfer_prompt": "ماذا تتوقع عند زاوية 180°؟",
    "module_spec": {"outputs": ["lit_fraction"]},
    "checks": [
        {
            "id": "quarter_phase",
            "kind": "numeric",
            "inputs": [{"name": "angle_deg", "value": 90}],
            "output": "lit_fraction",
            "expected": 0.5,
            "tolerance": 0.02,
            "unit": "ratio",
        },
        {
            "id": "full_phase",
            "kind": "numeric",
            "inputs": [{"name": "angle_deg", "value": 180}],
            "output": "lit_fraction",
            "expected": 1.0,
            "tolerance": 0.02,
            "unit": "ratio",
        },
    ],
    "suggestions": [],
}

VALID_MODULE_OUTPUT = {
    "module_js": "window.LayshSimulation = {};",
    "output_names": ["lit_fraction"],
    "brief_summary": "يرسم تغير الجزء المضيء مع زاوية المدار.",
    "assumptions": ["مدار دائري مبسط"],
}
